# Generated by Django 4.0 on 2023-03-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=300)),
                ('browser', models.CharField(max_length=300)),
                ('os_info', models.CharField(max_length=300)),
                ('device_pr', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=300)),
                ('ip', models.CharField(max_length=300)),
                ('subdivisions', models.CharField(max_length=300)),
                ('latitude', models.CharField(max_length=300)),
                ('longitude', models.CharField(max_length=300)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
