# Generated by Django 4.0 on 2023-03-28 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_rename_subdivisions_visitorsinformation_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='city',
        ),
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='image',
        ),
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='visitorsinformation',
            name='region',
        ),
    ]
