# Generated by Django 4.0 on 2023-03-28 12:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_remove_visitorsinformation_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorsinformation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
