# Generated by Django 4.0 on 2023-04-10 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0005_visitorsinformation_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorsinformation',
            options={'ordering': ['-created_at']},
        ),
    ]
